info:
  description: Internal configuration of app.
options:
  debug: false # <- only set to true when developing.
  show-side-menu: false
  ################
  # Times in ms before bot response (inline resp. menu) are deleted.
  # Use negative (-) values, if no deletion should occur.
  ################
  timeout:       -5000
  timeout-menu: -10000
# ------------------------------------------------------------------------------------------------
# SUPPORTED LANGUAGES
# Note: use ISO-639-1 alpha-2 format; e.g. uk (not ua) for Ukrainian.
# ------------------------------------------------------------------------------------------------
languages:
  - en
  - de
  - uk
  - pl
  - ru
default-language: en
# ------------------------------------------------------------------------------------------------
# COMMANDS
# NOTE structure is as follows:
#
#   command:     '/...'
#   keyword:     keyword for call_back_data AND on screen message.
#   match:       regex to match commands.
#   strict:      true => only those commands accepted, which address bot with @<botname>
#   rights:      [ list of user stati who can use this command ]
#   menu:        true/false - should appear in big menu?
#   side-menu:
#   * redirect:  if should be used as redirect command.
#   * url:       redirect url
#   * new_row:   true => button should be placed on new row
#
# Note: each keyword-attribute *must* correspond to a key from assets/translations.yml
# Note: rights can be any subset of
#  [creator, administrator, member]
# ------------------------------------------------------------------------------------------------
commands:
  ## special commandos
  - command:   '/hello'
    keyword:   'hello-world-message'
    match:     '^\/(hello|helloworld|hello-world)'
    strict:    false
    rights:    [administrator, creator]
    menu:      false
    side-menu: false
  - &ref_pin_command
    command:   '/pin'
    keyword:   'pinned-message'
    match:     '^\/(pin|pinned)$'
    strict:    false
    rights:    [administrator, creator]
    menu:      false
    side-menu: false
  - <<: *ref_pin_command
    command:   '/pin-all'
    match:     '^\/(pin|pinned)(-all|-all-languages)$'
  - command:   '/start'
    keyword:   'start-message'
    match:     '^\/start\s*$'
    strict:    false
    rights:    [administrator, creator]
    menu:      false
    side-menu: false
  - command:   '/help'
    keyword:   'help-message'
    match:     '^\/(help|info)$'
    strict:    false
    rights:    [administrator, creator]
    menu:      false
    side-menu: false
  ## menu commands
  ## 1st row
  - command:   '/transport'
    keyword:   transport
    match:     '^\/(transport|travel).*$'
    strict:    false
    rights:    [administrator, creator]
    menu:      true
    side-menu: true
    redirect:  true
    url:       '@transport_leipzig_ukraine'
    new_row:   true
  - command:   '/housing'
    keyword:   housing
    match:     '^\/(housing|shelter|obdach|accom.*)$'
    strict:    false
    rights:    [administrator, creator]
    menu:      true
    side-menu: true
    redirect:  true
    url:       '@accomodation_leipzig_ukraine'
  ## 2nd row
  - command:   '/translations'
    rights:    [administrator, creator]
    keyword:   translations
    match:     '^\/(translation(s|)|language(s|)|dolmetsch.*)$'
    strict:    false
    menu:      true
    side-menu: true
    redirect:  true
    url:       '@translators_leipzig_ukraine'
    new_row:   true
  - command:   '/legal'
    rights:    [administrator, creator]
    keyword:   legal
    match:     '^\/(legal.*|law|jura|jurist.*|rights)$'
    strict:    false
    menu:      true
    side-menu: true
    redirect:  true
    url:       '@legal_leipzig_ukraine'
  ## 3rd row
  - command:   '/donations'
    rights:    [administrator, creator]
    keyword:   donations
    match:     '^\/(donation|charity|spenden|give.*|gifts)$'
    strict:    false
    menu:      true
    side-menu: true
    redirect:  true
    url:       '@donations_leipzig_ukraine'
    new_row:   true
  ## 4th row
  - command:   '/homepage'
    rights:    [administrator, creator]
    keyword:   homepage
    match:     '^\/(homepage|web|website|webpage)$'
    strict:    false
    menu:      true
    side-menu: true
    redirect:  true
    url:       'http://leipzig-helps-ukraine.de/'
    new_row:   true
  - command:   '/feedback'
    rights:    [administrator, creator]
    keyword:   feedback
    match:     '^\/(feedback|review)$'
    strict:    false
    menu:      true
    side-menu: true
    redirect:  true
    url:       '@feedback_leipzig_ukraine'
