info:
  description: Internal configuration of app.
options:
  debug: false # <- only set to true when developing.
  ################
  # Times in ms before bot response (inline resp. menu) are deleted.
  # Use value -1, if no deletion should occur.
  ################
  timeout:       5000
  timeout-menu: 10000
# ------------------------------------------------------------------------------------------------
# SUPPORTED LANGUAGES
# Note: use ISO-639-1 alpha-2 format; e.g. uk (not ua) for Ukrainian.
# ------------------------------------------------------------------------------------------------
languages:
  - de
  - en
  - pl
  - ru
  - uk
default-language: en
# ------------------------------------------------------------------------------------------------
# COMMANDS
# Structure:
#   command:
#   keyword: (must be a key from the assets/translations.yml file)
#   group:
#   new_row: optional - if true, indicates that button should be placed on new row.
# Note: each keyword-attribute *must* correspond to a key from assets/translations.yml
# ------------------------------------------------------------------------------------------------
commands:
  ## 1st row:
  - command:   '/transport'
    keyword:   transport
    group:     '@transport_leipzig_ukraine'
    new_row:   true
  - command:   '/housing'
    keyword:   housing
    group:     '@accomodation_leipzig_ukraine'
  ## 2nd row:
  - command:   '/translations'
    keyword:   translations
    group:     '@interpreter_leipzig_ukraine'
    new_row:   true
  - command:   '/legal'
    keyword:   legal
    group:     '@legal_leipzig_ukraine'
  ## 1st row:
  - command:   '/donations'
    keyword:   donations
    group:     '@donations_leipzig_ukraine'
    new_row:   true
