info:
  description: |-
    Internal configuration of app based on schema defined in models/config.yaml.
app-options:
  ################
  # only set to true during development. Do NOT commit with 'debug: true'!
  debug: false
  ################
  # defines the default language of all commands as a fall back:
  default-language: uk # NOTE: uk = Ukrainian
  ################
  # logging messages are censored. With
  # true => complete censoring of any potential data
  # false => partial censoring, but enough to prevent sensitive information from being logged.
  full-censor: false      # regards context
  full-censor-user: false # regards user (caller)
  ################
  # true => shows suggests when user starts typing /...
  show-side-menu: true
  ################
  # true => listens to all texts; false => only listens to messages starting with /...
  listen-to-text: true
  ################
  # true => calls to bot will be deleted before reply
  # false => calls to bot will be retained
  # (NOTE: only use false, if bot can edit messages --- likely not the case!)
  delete-calls: true
  ################
  # maximum age of messages in ms.
  # All messages that occur 'too long' ago, will be ignored.
  message-expiry: 30000
  ################
  # NOTE: The following parameters are no longer in use.
  # Times in ms before bot response (inline resp. menu) are deleted.
  # Use negative (-) values, if no deletion should occur.
  timeout:       5000
  timeout-menu: 10000
  ################
# ------------------------------------------------------------------------------------------------
# SUPPORTED LANGUAGES
# NOTE: use ISO-639-1 alpha-2 format; e.g. uk (not ua) for Ukrainian.
# NOTE: keep this order!
# ------------------------------------------------------------------------------------------------
language-codes:
  - code: uk
    pattern: '^(uk|ukr|ua)$'
  - code: de
    pattern: '^(de|deu)$'
  - code: en
    pattern: '^(en)$'
  - code: pl
    pattern: '^(pl)$'
  - code: ru
    pattern: '^(ru)$'
# ------------------------------------------------------------------------------------------------
# COMMANDS
# NOTE: each keyword-attribute *must* correspond to a key from assets/translations.yml
# NOTE: rights can be any subset of
#  [creator, administrator, member]
# ------------------------------------------------------------------------------------------------
commands:
  ################################################################
  # START special commandos
  - aspects:
      command: '/hello'
      rights:  [administrator, creator]
      strict:  true
      match:   '^hello(-?world)?$'
    text:
      keyword: hello-world-message
  - aspects:
      command: '/help'
      rights:  [administrator, creator]
      strict:  true
      match:   '^help$'
    side-menu:
      keyword: help-message
    text:
      keyword: help-message
  # END special commands
  ################################################################
  # START menu commands
  ## 1st row
  - aspects:
      command:  '/arrival'
      rights:   [administrator, creator]
      strict:   true
      match:    '^(arrivals?|ankunft)$'
    redirect:
      group:  '@arrival_leipzig_ukraine'
    menu:
      keyword: arrival
      new_row: true
    side-menu:
      keyword: arrival-desc
    text:
      keyword: redirect-message
  - aspects:
      command:  '/accomodation'
      rights:   [administrator, creator]
      strict:   true
      match:    '^(housing|a(c+)o(m+)odation|shelter|obdach)$'
    redirect:
      group: '@accomodation_leipzig_ukraine'
    menu:
      keyword: housing
    side-menu:
      keyword: housing-desc
    text:
      keyword: redirect-message
  - aspects:
      command:  '/translations'
      rights:   [administrator, creator]
      strict:   true
      match:    '^(translat.*|language(s?)|dolmetsch.*)$'
    redirect:
      group: '@translators_leipzig_ukraine'
    menu:
      keyword: translations
    side-menu:
      keyword: translations-desc
    text:
      keyword: redirect-message
  ## 2nd row
  - aspects:
      command:  '/donations'
      rights:   [administrator, creator]
      strict:   true
      match:    '^(donation(s?)|charit(y|ies)|spenden|give|giving|gift(s?))$'
    redirect:
      group: '@donations_leipzig_ukraine'
    menu:
      keyword: donations
      new_row: true
    side-menu:
      keyword: donations-desc
    text:
      keyword: redirect-message
  - aspects:
      command:  '/family'
      rights:   [administrator, creator]
      strict:   true
      match:    '^(family|kids?|child(ren)?|familie)$'
    redirect:
      group:  '@kids_leipzig_ukraine'
    menu:
      keyword: family
    side-menu:
      keyword: family-desc
    text:
      keyword: redirect-message
  - aspects:
      command:  '/animals'
      rights:   [administrator, creator]
      strict:   true
      match:    '^(animals?|pets?)$'
    redirect:
      group:  '@animals_leipzig_ukraine'
    menu:
      keyword: animals
    side-menu:
      keyword: animals-desc
    text:
      keyword: redirect-message
  ## 3rd row
  - aspects:
      command:  '/jobs'
      rights:   [administrator, creator]
      strict:   true
      match:    '^(jobs?|work|employment|arbeit|arbeitss?uche)$'
    redirect:
      group: '@jobs_leipzig_ukraine'
    menu:
      keyword: jobs
      new_row: true
    side-menu:
      keyword: jobs-desc
    text:
      keyword: redirect-message
  - aspects:
      command:  '/legal'
      rights :  [administrator, creator]
      strict:   true
      match:    '^(legal.*|law|jura|jurist.*|rights)$'
    redirect:
      group: '@legal_leipzig_ukraine'
    menu:
      keyword: legal
    side-menu:
      keyword: legal-desc
    text:
      keyword: redirect-message
  - aspects:
      command:  '/homepage'
      rights:   [administrator, creator]
      strict:   true
      match:    '^(homepage|web|website|webpage)$'
    redirect:
      url: http://leipzig-helps-ukraine.de/
    menu:
        keyword: homepage
    side-menu:
      keyword: homepage-desc
    text:
      keyword: redirect-message
  ## Following are NOT in menu:
  - aspects:
      command:  '/transport'
      rights:   [administrator, creator]
      strict:   true
      match:    '^(transport|travel).*$'
    redirect:
      group: '@transport_leipzig_ukraine'
    side-menu:
      keyword: transport-desc
    text:
      keyword: redirect-message
  - aspects:
      command:  '/feedback'
      rights :  [administrator, creator]
      strict:   true
      match:    '^(feedback|review)$'
    redirect:
      group: '@feedback_leipzig_ukraine'
    side-menu:
      keyword: feedback-desc
    text:
      keyword: redirect-message
  - aspects:
      command:  '/ethermap'
      rights:   [administrator, creator]
      strict:   true
      match:    '^ethermap$'
    redirect:
      url: 'https://getethermap.org/m/leipzig-donation-for-ukraine'
    side-menu:
      keyword: donations-map-desc
    text:
      keyword: redirect-message-donations-map
  # END menu commands
  ################################################################
  # START special commands - variants of /pin
  - aspects: &ref_command_pin
      command: '/pin'
      rights:  [administrator, creator]
      strict:  true
      match:   '^pin(ned)?$'
    side-menu:
      keyword: pinned-short
    text:
      keyword: pinned-message
  - aspects:
      <<: *ref_command_pin
      command: '/pin_uk'
      match:   '^pin(ned)?[-_](uk|ukr|ua)$'
    side-menu:
      lang:    uk
      keyword: pinned-short
    text:
      lang:    uk
      keyword: pinned-message
  - aspects:
      <<: *ref_command_pin
      command: '/pin_de'
      match:   '^pin(ned)?[-_](de|deu)$'
    text:
      lang:    de
      keyword: pinned-message
  - aspects:
      <<: *ref_command_pin
      command: '/pin_en'
      match:   '^pin(ned)?[-_](en)$'
    side-menu:
      lang:    en
      keyword: pinned-short
    text:
      lang:    en
      keyword: pinned-message
  # END variants of /pin
  ################################################################
