info:
  description: Internal configuration of app.
options:
  ################
  # only set to true during development. Do NOT commit with 'debug: true'!
  debug: false
  ################
  # true => shows suggests when user starts typing /...
  show-side-menu: true
  ################
  # true => listens to all texts; false => only listens to messages starting with /...
  listen-to-text: true
  ################
  # true => calls to bot will be deleted before reply
  # false => calls to bot will be retained
  # (NOTE: only use false, if bot can edit messages --- likely not the case!)
  delete-calls: true
  ################
  # maximum age of messages in ms.
  # All messages that occur 'too long' ago, will be ignored.
  message-expiry: 10000
  ################
  # NOTE: The following parameters are no longer in use.
  # Times in ms before bot response (inline resp. menu) are deleted.
  # Use negative (-) values, if no deletion should occur.
  timeout:       -5000
  timeout-menu: -10000
  ################
# ------------------------------------------------------------------------------------------------
# SUPPORTED LANGUAGES
# Note: use ISO-639-1 alpha-2 format; e.g. uk (not ua) for Ukrainian.
# ------------------------------------------------------------------------------------------------
languages:
  - en
  - de
  - uk
  - pl
  - ru
default-language: &ref_default_lang en
# ------------------------------------------------------------------------------------------------
# COMMANDS
# NOTE structure is as follows:
#
#    aspects: # <- defines basic attributes fo command
#      command:  '/...' # exact form of command to be registered.
#      rights:   # [ list of user stati who can use this command ]
#      strict:   # true => only those commands accepted, which address bot with @<botname>
#      match:    # regex by which bot should recognise user input as command (after removing @ + trimming)
#    * redirect: # url => if included command treated as redirection to url.
#  * menu: # <- add this, if command should appear as a button in a menu
#      keyword: # kw for text to appear in menu
#    * lang:    # forces language of text (missing => use caller's language)
#    * new_row: # true => button should be placed on new row; default = false.
#  * side-menu: # <- add this, if command should appear in side-menu (suggestions)
#      keyword: # kw for text to appear in side-menu
#    * lang:    # forces language of text (missing => use caller's language)
#    text: # <- for handling of inline text
#      keyword: # kw for text to appear inline
#    * lang:    # forces language of text (missing => use caller's language)
#
# (* = optional)
#
# Note: each keyword-attribute *must* correspond to a key from assets/translations.yml
# Note: rights can be any subset of
#  [creator, administrator, member]
# ------------------------------------------------------------------------------------------------
commands:
  ################################################################
  # START special commandos
  - aspects:
      command: '/hello'
      rights:  [administrator, creator]
      strict:  true
      match:   '^hello(-?world)?$'
    text:
      keyword: hello-world-message
  - aspects:
      command: '/help'
      rights:  [administrator, creator]
      strict:  true
      match:   '^help$'
    side-menu:
      keyword: help-message
    text:
      keyword: help-message
  # END special commands
  ################################################################
  # START menu commands
  ## 1st row
  - aspects:
      command:  '/transport'
      rights:   [administrator, creator]
      strict:   true
      match:    '^(transport|travel).*$'
      redirect: '@transport_leipzig_ukraine'
    menu:
      keyword: transport
      new_row: true
    side-menu:
      keyword: transport-desc
    text:
      keyword: redirect-message
  - aspects:
      command:  '/housing'
      rights:   [administrator, creator]
      strict:   true
      match:    '^(housing|a(c+)o(m+)odation|shelter|obdach)$'
      redirect: '@accomodation_leipzig_ukraine'
    menu:
      keyword: housing
      new_row: true
    side-menu:
      keyword: housing-desc
    text:
      keyword: redirect-message
  ## 2nd row
  - aspects:
      command:  '/translations'
      rights:   [administrator, creator]
      strict:   true
      match:    '^(translation(s?)|language(s?)|dolmetsch.*)$'
      redirect: '@translators_leipzig_ukraine'
    menu:
      keyword: translations
      new_row: true
    side-menu:
      keyword: translations-desc
    text:
      keyword: redirect-message
  - aspects:
      command:  '/legal'
      rights :  [administrator, creator]
      strict:   true
      redirect: '@legal_leipzig_ukraine'
      match:    '^(legal.*|law|jura|jurist.*|rights)$'
    menu:
      keyword: legal
    side-menu:
      keyword: legal-desc
    text:
      keyword: redirect-message
  ## 3rd row
  - aspects:
      command:  '/donations'
      rights:   [administrator, creator]
      strict:   true
      match:    '^(donation(s?)|charit(y|ies)|spenden|give|giving|gift(s?))$'
      redirect: '@donations_leipzig_ukraine'
    menu:
      keyword: donations
      new_row: true
    side-menu:
      keyword: donations-desc
    text:
      keyword: redirect-message
  ## 4th row
  - aspects:
      command:  '/homepage'
      rights:   [administrator, creator]
      strict:   true
      match:    '^(homepage|web|website|webpage)$'
      redirect: http://leipzig-helps-ukraine.de/
    menu:
      keyword: homepage
      new_row: true
    side-menu:
      keyword: homepage-desc
    text:
      keyword: redirect-message
    new_row:   true
  - aspects:
      command:  '/feedback'
      rights :  [administrator, creator]
      strict:   true
      redirect: '@feedback_leipzig_ukraine'
      match:    '^(feedback|review)$'
    menu:
      keyword: feedback
    side-menu:
      keyword: feedback-desc
    text:
      keyword: redirect-message
  # END menu commands
  ################################################################
  # START special commands - variants of /pin
  - aspects: &ref_command_pin
      command: '/pin'
      rights:  [administrator, creator]
      strict:  true
      match:   '^pin(ned)?$'
    side-menu:
      lang:    *ref_default_lang
      keyword: pinned-short
    text:
      keyword: pinned-message
  - aspects:
      <<: *ref_command_pin
      command: '/pin_de'
      match:   '^pin(ned)?[-_](de|deu)$'
    side-menu:
      lang:    de
      keyword: pinned-short
    text:
      lang:    de
      keyword: pinned-message
  - aspects:
      <<: *ref_command_pin
      command: '/pin_uk'
      match:   '^pin(ned)?[-_](uk|ukr|ua)$'
    side-menu:
      lang:    uk
      keyword: pinned-short
    text:
      lang:    uk
      keyword: pinned-message
  # END variants of /pin
  ################################################################
